ARG NODE_VERSION=24
ARG PNPM_VERSION=11.21.0

# 1. BASE: Enable Corepack & pnpm
FROM node:${NODE_VERSION}-bookworm-slim AS base
WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

# 2. DEVELOPMENT
FROM base AS development
ENV NODE_ENV=development

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]
